extends: google
env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 7
  sourceType: module
rules:
  object-curly-spacing:
    - 2
    - always
  semi:
    - 2
    - never
  max-len: 
    - 2 
    - 120
  no-trailing-spaces:
    - 2
    - skipBlankLines: true